### ISSUE TITLE
Is there an example of sending a command to Atem?

### ISSUE THREAD

**Issue by CattivoLe** [Dev1an/Swift-Atem#2]

**Comment by Dev1an** [comment]
To send a message to the atem start with the example from the readme.md :

```Swift
let controller = try Controller(ipAddress: "10.1.0.67")
```

Then call [`send(message:)`](https://dev1an.github.io/Swift-Atem/Classes/Controller.html#/s:4Atem10ControllerC4sendyAA12Serializable_p7message_tF) on the controller:

```Swift
controller.send(message: ChangeTransitionPosition(to: 5000))
```

Please let me know if this works... because I didn't try out this sample code.

**Comment by CattivoLe** [comment]
Thanks, this works great!!

**Comment by Dev1an** [comment]
OK I will add it to the readme then. When going through the docs I saw that the constructors for most of the other messages were not public yet (for example there is no public init for [ChangePreviewBus](https://dev1an.github.io/Swift-Atem/Structs/ChangePreviewBus.html)). Would you like to add this, test it and create a pull request for that?

**Comment by CattivoLe** [comment]
I would very much like to add this, but unfortunately I do not quite yet understand how to do it,,
